### ISSUE TITLE
Using the groupproj file, path didn't resolve correctly

### ISSUE THREAD

**Issue by ClaytonMcCrayFC** [ClaytonMcCray/fcintellibuild#2]
Paths to cbproj files found via the groupproj file resolved with the repo directory cut out of the path. So if it was `C:\path\to\repo\and\proj`, it would try and open `C:\path\to\and\proj`.

**Comment by ClaytonMcCray** [comment]
Fixed by changing the working directory to the groupproj directory and then moving back when finished.
